import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

// Supported languages
export type Language = "es" | "en" | "pt" | "fr" | "de" | "it" | "zh" | "ja" | "ko" | "ar" | "hi" | "ru";

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
];

// Translation keys for the app
export type TranslationKey = keyof typeof translations.es;

// Complete translations for the app
export const translations = {
  es: {
    // Navigation
    "nav.home": "Inicio",
    "nav.curriculum": "Currículo",
    "nav.grammar": "Gramática",
    "nav.vocabulary": "Vocabulario",
    "nav.practice": "Práctica",
    "nav.conversation": "Conversación",
    "nav.tests": "Exámenes",
    "nav.articles": "Artículos",
    "nav.settings": "Configuración",
    
    // Common
    "common.back": "Volver",
    "common.next": "Siguiente",
    "common.previous": "Anterior",
    "common.start": "Comenzar",
    "common.continue": "Continuar",
    "common.finish": "Finalizar",
    "common.correct": "¡Correcto!",
    "common.incorrect": "Incorrecto",
    "common.score": "Puntuación",
    "common.level": "Nivel",
    "common.exercise": "Ejercicio",
    "common.exercises": "Ejercicios",
    "common.of": "de",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "¡Éxito!",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "common.none": "Ninguno",
    "common.yes": "Sí",
    "common.no": "No",
    
    // Dashboard
    "dashboard.welcome": "¡Bienvenido de nuevo!",
    "dashboard.todayLesson": "Lección de hoy",
    "dashboard.dailyGoal": "Meta diaria",
    "dashboard.streak": "Racha",
    "dashboard.xp": "Experiencia",
    "dashboard.progress": "Tu progreso",
    "dashboard.continuelearning": "Continuar aprendiendo",
    "dashboard.adventureMap": "Mapa de Aventura",
    "dashboard.aiTutor": "Tutor IA",
    "dashboard.articleLibrary": "Biblioteca de Artículos",
    
    // Skill Lesson
    "lesson.overview": "Vista General",
    "lesson.practice": "Práctica",
    "lesson.objectives": "Objetivos de Aprendizaje",
    "lesson.content": "Contenido a Practicar",
    "lesson.startPractice": "Comenzar Práctica",
    "lesson.beforeAnswer": "Antes de responder, recuerda:",
    "lesson.listenQuestion": "Escuchar pregunta",
    "lesson.readArticle": "Leer artículo completo",
    "lesson.correctAnswers": "correctas",
    "lesson.incorrectAnswers": "incorrectas",
    "lesson.explanation": "Explicación",
    "lesson.nextExercise": "Siguiente ejercicio",
    "lesson.complete": "¡Lección completada!",
    "lesson.earnedXP": "Has ganado XP",
    "lesson.backHome": "Volver al inicio",
    "lesson.continueCurriculum": "Continuar currículo",
    "lesson.excellentWork": "¡Excelente trabajo, aventurero!",
    "lesson.keepPracticing": "Sigue practicando para mejorar",
    
    // Articles
    "articles.library": "Biblioteca de Artículos",
    "articles.introduction": "Introducción",
    "articles.examples": "Ejemplos Prácticos",
    "articles.commonMistakes": "Errores Comunes a Evitar",
    "articles.practiceExercises": "Ejercicios de Práctica",
    "articles.summary": "Resumen",
    "articles.relatedArticles": "Artículos Relacionados",
    "articles.tableOfContents": "Contenido",
    "articles.readTime": "min de lectura",
    "articles.showAnswer": "Ver respuesta",
    "articles.hideAnswer": "Ocultar respuesta",
    "articles.hint": "Pista",
    "articles.answer": "Respuesta",
    
    // Levels
    "level.beginner": "Principiante",
    "level.elementary": "Elemental",
    "level.intermediate": "Intermedio",
    "level.upperIntermediate": "Intermedio Alto",
    "level.advanced": "Avanzado",
    "level.mastery": "Maestría",
    "level.novice": "Novato",
    "level.apprentice": "Aprendiz",
    "level.adventurer": "Aventurero",
    "level.warrior": "Guerrero",
    "level.master": "Maestro",
    "level.legend": "Leyenda",
    
    // Categories
    "category.grammar": "Gramática",
    "category.vocabulary": "Vocabulario",
    "category.speaking": "Expresión Oral",
    "category.listening": "Comprensión Auditiva",
    "category.reading": "Comprensión Lectora",
    "category.writing": "Expresión Escrita",
    
    // Language selector
    "language.select": "Seleccionar idioma",
    "language.current": "Idioma actual",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.curriculum": "Curriculum",
    "nav.grammar": "Grammar",
    "nav.vocabulary": "Vocabulary",
    "nav.practice": "Practice",
    "nav.conversation": "Conversation",
    "nav.tests": "Tests",
    "nav.articles": "Articles",
    "nav.settings": "Settings",
    
    // Common
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.start": "Start",
    "common.continue": "Continue",
    "common.finish": "Finish",
    "common.correct": "Correct!",
    "common.incorrect": "Incorrect",
    "common.score": "Score",
    "common.level": "Level",
    "common.exercise": "Exercise",
    "common.exercises": "Exercises",
    "common.of": "of",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success!",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
    "common.none": "None",
    "common.yes": "Yes",
    "common.no": "No",
    
    // Dashboard
    "dashboard.welcome": "Welcome back!",
    "dashboard.todayLesson": "Today's lesson",
    "dashboard.dailyGoal": "Daily goal",
    "dashboard.streak": "Streak",
    "dashboard.xp": "Experience",
    "dashboard.progress": "Your progress",
    "dashboard.continuelearning": "Continue learning",
    "dashboard.adventureMap": "Adventure Map",
    "dashboard.aiTutor": "AI Tutor",
    "dashboard.articleLibrary": "Article Library",
    
    // Skill Lesson
    "lesson.overview": "Overview",
    "lesson.practice": "Practice",
    "lesson.objectives": "Learning Objectives",
    "lesson.content": "Content to Practice",
    "lesson.startPractice": "Start Practice",
    "lesson.beforeAnswer": "Before answering, remember:",
    "lesson.listenQuestion": "Listen to question",
    "lesson.readArticle": "Read full article",
    "lesson.correctAnswers": "correct",
    "lesson.incorrectAnswers": "incorrect",
    "lesson.explanation": "Explanation",
    "lesson.nextExercise": "Next exercise",
    "lesson.complete": "Lesson complete!",
    "lesson.earnedXP": "You earned XP",
    "lesson.backHome": "Back to home",
    "lesson.continueCurriculum": "Continue curriculum",
    "lesson.excellentWork": "Excellent work, adventurer!",
    "lesson.keepPracticing": "Keep practicing to improve",
    
    // Articles
    "articles.library": "Article Library",
    "articles.introduction": "Introduction",
    "articles.examples": "Practical Examples",
    "articles.commonMistakes": "Common Mistakes to Avoid",
    "articles.practiceExercises": "Practice Exercises",
    "articles.summary": "Summary",
    "articles.relatedArticles": "Related Articles",
    "articles.tableOfContents": "Contents",
    "articles.readTime": "min read",
    "articles.showAnswer": "Show answer",
    "articles.hideAnswer": "Hide answer",
    "articles.hint": "Hint",
    "articles.answer": "Answer",
    
    // Levels
    "level.beginner": "Beginner",
    "level.elementary": "Elementary",
    "level.intermediate": "Intermediate",
    "level.upperIntermediate": "Upper Intermediate",
    "level.advanced": "Advanced",
    "level.mastery": "Mastery",
    "level.novice": "Novice",
    "level.apprentice": "Apprentice",
    "level.adventurer": "Adventurer",
    "level.warrior": "Warrior",
    "level.master": "Master",
    "level.legend": "Legend",
    
    // Categories
    "category.grammar": "Grammar",
    "category.vocabulary": "Vocabulary",
    "category.speaking": "Speaking",
    "category.listening": "Listening",
    "category.reading": "Reading",
    "category.writing": "Writing",
    
    // Language selector
    "language.select": "Select language",
    "language.current": "Current language",
  },
  pt: {
    "nav.home": "Início",
    "nav.curriculum": "Currículo",
    "nav.grammar": "Gramática",
    "nav.vocabulary": "Vocabulário",
    "nav.practice": "Prática",
    "nav.conversation": "Conversação",
    "nav.tests": "Testes",
    "nav.articles": "Artigos",
    "nav.settings": "Configurações",
    "common.back": "Voltar",
    "common.next": "Próximo",
    "common.previous": "Anterior",
    "common.start": "Iniciar",
    "common.continue": "Continuar",
    "common.finish": "Finalizar",
    "common.correct": "Correto!",
    "common.incorrect": "Incorreto",
    "common.score": "Pontuação",
    "common.level": "Nível",
    "common.exercise": "Exercício",
    "common.exercises": "Exercícios",
    "common.of": "de",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso!",
    "common.cancel": "Cancelar",
    "common.save": "Salvar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "common.none": "Nenhum",
    "common.yes": "Sim",
    "common.no": "Não",
    "dashboard.welcome": "Bem-vindo de volta!",
    "dashboard.todayLesson": "Lição de hoje",
    "dashboard.dailyGoal": "Meta diária",
    "dashboard.streak": "Sequência",
    "dashboard.xp": "Experiência",
    "dashboard.progress": "Seu progresso",
    "dashboard.continuelearning": "Continuar aprendendo",
    "dashboard.adventureMap": "Mapa de Aventura",
    "dashboard.aiTutor": "Tutor IA",
    "dashboard.articleLibrary": "Biblioteca de Artigos",
    "lesson.overview": "Visão Geral",
    "lesson.practice": "Prática",
    "lesson.objectives": "Objetivos de Aprendizagem",
    "lesson.content": "Conteúdo para Praticar",
    "lesson.startPractice": "Iniciar Prática",
    "lesson.beforeAnswer": "Antes de responder, lembre-se:",
    "lesson.listenQuestion": "Ouvir pergunta",
    "lesson.readArticle": "Ler artigo completo",
    "lesson.correctAnswers": "corretas",
    "lesson.incorrectAnswers": "incorretas",
    "lesson.explanation": "Explicação",
    "lesson.nextExercise": "Próximo exercício",
    "lesson.complete": "Lição concluída!",
    "lesson.earnedXP": "Você ganhou XP",
    "lesson.backHome": "Voltar ao início",
    "lesson.continueCurriculum": "Continuar currículo",
    "lesson.excellentWork": "Excelente trabalho, aventureiro!",
    "lesson.keepPracticing": "Continue praticando para melhorar",
    "articles.library": "Biblioteca de Artigos",
    "articles.introduction": "Introdução",
    "articles.examples": "Exemplos Práticos",
    "articles.commonMistakes": "Erros Comuns a Evitar",
    "articles.practiceExercises": "Exercícios de Prática",
    "articles.summary": "Resumo",
    "articles.relatedArticles": "Artigos Relacionados",
    "articles.tableOfContents": "Conteúdo",
    "articles.readTime": "min de leitura",
    "articles.showAnswer": "Ver resposta",
    "articles.hideAnswer": "Ocultar resposta",
    "articles.hint": "Dica",
    "articles.answer": "Resposta",
    "level.beginner": "Iniciante",
    "level.elementary": "Elementar",
    "level.intermediate": "Intermediário",
    "level.upperIntermediate": "Intermediário Alto",
    "level.advanced": "Avançado",
    "level.mastery": "Maestria",
    "level.novice": "Novato",
    "level.apprentice": "Aprendiz",
    "level.adventurer": "Aventureiro",
    "level.warrior": "Guerreiro",
    "level.master": "Mestre",
    "level.legend": "Lenda",
    "category.grammar": "Gramática",
    "category.vocabulary": "Vocabulário",
    "category.speaking": "Expressão Oral",
    "category.listening": "Compreensão Auditiva",
    "category.reading": "Compreensão Leitora",
    "category.writing": "Expressão Escrita",
    "language.select": "Selecionar idioma",
    "language.current": "Idioma atual",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.curriculum": "Programme",
    "nav.grammar": "Grammaire",
    "nav.vocabulary": "Vocabulaire",
    "nav.practice": "Pratique",
    "nav.conversation": "Conversation",
    "nav.tests": "Tests",
    "nav.articles": "Articles",
    "nav.settings": "Paramètres",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.start": "Commencer",
    "common.continue": "Continuer",
    "common.finish": "Terminer",
    "common.correct": "Correct!",
    "common.incorrect": "Incorrect",
    "common.score": "Score",
    "common.level": "Niveau",
    "common.exercise": "Exercice",
    "common.exercises": "Exercices",
    "common.of": "de",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès!",
    "common.cancel": "Annuler",
    "common.save": "Sauvegarder",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.all": "Tous",
    "common.none": "Aucun",
    "common.yes": "Oui",
    "common.no": "Non",
    "dashboard.welcome": "Bienvenue!",
    "dashboard.todayLesson": "Leçon du jour",
    "dashboard.dailyGoal": "Objectif quotidien",
    "dashboard.streak": "Série",
    "dashboard.xp": "Expérience",
    "dashboard.progress": "Votre progression",
    "dashboard.continuelearning": "Continuer à apprendre",
    "dashboard.adventureMap": "Carte d'Aventure",
    "dashboard.aiTutor": "Tuteur IA",
    "dashboard.articleLibrary": "Bibliothèque d'Articles",
    "lesson.overview": "Vue d'ensemble",
    "lesson.practice": "Pratique",
    "lesson.objectives": "Objectifs d'apprentissage",
    "lesson.content": "Contenu à pratiquer",
    "lesson.startPractice": "Commencer la pratique",
    "lesson.beforeAnswer": "Avant de répondre, rappelez-vous:",
    "lesson.listenQuestion": "Écouter la question",
    "lesson.readArticle": "Lire l'article complet",
    "lesson.correctAnswers": "correctes",
    "lesson.incorrectAnswers": "incorrectes",
    "lesson.explanation": "Explication",
    "lesson.nextExercise": "Exercice suivant",
    "lesson.complete": "Leçon terminée!",
    "lesson.earnedXP": "Vous avez gagné XP",
    "lesson.backHome": "Retour à l'accueil",
    "lesson.continueCurriculum": "Continuer le programme",
    "lesson.excellentWork": "Excellent travail, aventurier!",
    "lesson.keepPracticing": "Continuez à pratiquer pour vous améliorer",
    "articles.library": "Bibliothèque d'Articles",
    "articles.introduction": "Introduction",
    "articles.examples": "Exemples Pratiques",
    "articles.commonMistakes": "Erreurs Courantes à Éviter",
    "articles.practiceExercises": "Exercices de Pratique",
    "articles.summary": "Résumé",
    "articles.relatedArticles": "Articles Connexes",
    "articles.tableOfContents": "Contenu",
    "articles.readTime": "min de lecture",
    "articles.showAnswer": "Voir la réponse",
    "articles.hideAnswer": "Cacher la réponse",
    "articles.hint": "Indice",
    "articles.answer": "Réponse",
    "level.beginner": "Débutant",
    "level.elementary": "Élémentaire",
    "level.intermediate": "Intermédiaire",
    "level.upperIntermediate": "Intermédiaire Supérieur",
    "level.advanced": "Avancé",
    "level.mastery": "Maîtrise",
    "level.novice": "Novice",
    "level.apprentice": "Apprenti",
    "level.adventurer": "Aventurier",
    "level.warrior": "Guerrier",
    "level.master": "Maître",
    "level.legend": "Légende",
    "category.grammar": "Grammaire",
    "category.vocabulary": "Vocabulaire",
    "category.speaking": "Expression Orale",
    "category.listening": "Compréhension Orale",
    "category.reading": "Compréhension Écrite",
    "category.writing": "Expression Écrite",
    "language.select": "Sélectionner la langue",
    "language.current": "Langue actuelle",
  },
  de: {
    "nav.home": "Startseite",
    "nav.curriculum": "Lehrplan",
    "nav.grammar": "Grammatik",
    "nav.vocabulary": "Vokabular",
    "nav.practice": "Übung",
    "nav.conversation": "Konversation",
    "nav.tests": "Tests",
    "nav.articles": "Artikel",
    "nav.settings": "Einstellungen",
    "common.back": "Zurück",
    "common.next": "Weiter",
    "common.previous": "Vorherige",
    "common.start": "Starten",
    "common.continue": "Fortfahren",
    "common.finish": "Beenden",
    "common.correct": "Richtig!",
    "common.incorrect": "Falsch",
    "common.score": "Punktzahl",
    "common.level": "Stufe",
    "common.exercise": "Übung",
    "common.exercises": "Übungen",
    "common.of": "von",
    "common.loading": "Laden...",
    "common.error": "Fehler",
    "common.success": "Erfolg!",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.search": "Suchen",
    "common.filter": "Filtern",
    "common.all": "Alle",
    "common.none": "Keine",
    "common.yes": "Ja",
    "common.no": "Nein",
    "dashboard.welcome": "Willkommen zurück!",
    "dashboard.todayLesson": "Heutige Lektion",
    "dashboard.dailyGoal": "Tagesziel",
    "dashboard.streak": "Serie",
    "dashboard.xp": "Erfahrung",
    "dashboard.progress": "Dein Fortschritt",
    "dashboard.continuelearning": "Weiter lernen",
    "dashboard.adventureMap": "Abenteuerkarte",
    "dashboard.aiTutor": "KI-Tutor",
    "dashboard.articleLibrary": "Artikelbibliothek",
    "lesson.overview": "Übersicht",
    "lesson.practice": "Übung",
    "lesson.objectives": "Lernziele",
    "lesson.content": "Zu übender Inhalt",
    "lesson.startPractice": "Übung starten",
    "lesson.beforeAnswer": "Bevor du antwortest, denke daran:",
    "lesson.listenQuestion": "Frage anhören",
    "lesson.readArticle": "Vollständigen Artikel lesen",
    "lesson.correctAnswers": "richtig",
    "lesson.incorrectAnswers": "falsch",
    "lesson.explanation": "Erklärung",
    "lesson.nextExercise": "Nächste Übung",
    "lesson.complete": "Lektion abgeschlossen!",
    "lesson.earnedXP": "Du hast XP verdient",
    "lesson.backHome": "Zurück zur Startseite",
    "lesson.continueCurriculum": "Lehrplan fortsetzen",
    "lesson.excellentWork": "Ausgezeichnete Arbeit, Abenteurer!",
    "lesson.keepPracticing": "Übe weiter, um dich zu verbessern",
    "articles.library": "Artikelbibliothek",
    "articles.introduction": "Einführung",
    "articles.examples": "Praktische Beispiele",
    "articles.commonMistakes": "Häufige Fehler zu Vermeiden",
    "articles.practiceExercises": "Übungsaufgaben",
    "articles.summary": "Zusammenfassung",
    "articles.relatedArticles": "Verwandte Artikel",
    "articles.tableOfContents": "Inhalt",
    "articles.readTime": "Min. Lesezeit",
    "articles.showAnswer": "Antwort zeigen",
    "articles.hideAnswer": "Antwort verstecken",
    "articles.hint": "Hinweis",
    "articles.answer": "Antwort",
    "level.beginner": "Anfänger",
    "level.elementary": "Elementar",
    "level.intermediate": "Mittelstufe",
    "level.upperIntermediate": "Obere Mittelstufe",
    "level.advanced": "Fortgeschritten",
    "level.mastery": "Meisterschaft",
    "level.novice": "Neuling",
    "level.apprentice": "Lehrling",
    "level.adventurer": "Abenteurer",
    "level.warrior": "Krieger",
    "level.master": "Meister",
    "level.legend": "Legende",
    "category.grammar": "Grammatik",
    "category.vocabulary": "Vokabular",
    "category.speaking": "Sprechen",
    "category.listening": "Hören",
    "category.reading": "Lesen",
    "category.writing": "Schreiben",
    "language.select": "Sprache auswählen",
    "language.current": "Aktuelle Sprache",
  },
  it: {
    "nav.home": "Home",
    "nav.curriculum": "Curriculum",
    "nav.grammar": "Grammatica",
    "nav.vocabulary": "Vocabolario",
    "nav.practice": "Pratica",
    "nav.conversation": "Conversazione",
    "nav.tests": "Test",
    "nav.articles": "Articoli",
    "nav.settings": "Impostazioni",
    "common.back": "Indietro",
    "common.next": "Avanti",
    "common.previous": "Precedente",
    "common.start": "Inizia",
    "common.continue": "Continua",
    "common.finish": "Termina",
    "common.correct": "Corretto!",
    "common.incorrect": "Sbagliato",
    "common.score": "Punteggio",
    "common.level": "Livello",
    "common.exercise": "Esercizio",
    "common.exercises": "Esercizi",
    "common.of": "di",
    "common.loading": "Caricamento...",
    "common.error": "Errore",
    "common.success": "Successo!",
    "common.cancel": "Annulla",
    "common.save": "Salva",
    "common.delete": "Elimina",
    "common.edit": "Modifica",
    "common.search": "Cerca",
    "common.filter": "Filtra",
    "common.all": "Tutti",
    "common.none": "Nessuno",
    "common.yes": "Sì",
    "common.no": "No",
    "dashboard.welcome": "Bentornato!",
    "dashboard.todayLesson": "Lezione di oggi",
    "dashboard.dailyGoal": "Obiettivo giornaliero",
    "dashboard.streak": "Serie",
    "dashboard.xp": "Esperienza",
    "dashboard.progress": "I tuoi progressi",
    "dashboard.continuelearning": "Continua a imparare",
    "dashboard.adventureMap": "Mappa dell'Avventura",
    "dashboard.aiTutor": "Tutor IA",
    "dashboard.articleLibrary": "Biblioteca Articoli",
    "lesson.overview": "Panoramica",
    "lesson.practice": "Pratica",
    "lesson.objectives": "Obiettivi di Apprendimento",
    "lesson.content": "Contenuto da Praticare",
    "lesson.startPractice": "Inizia Pratica",
    "lesson.beforeAnswer": "Prima di rispondere, ricorda:",
    "lesson.listenQuestion": "Ascolta domanda",
    "lesson.readArticle": "Leggi articolo completo",
    "lesson.correctAnswers": "corrette",
    "lesson.incorrectAnswers": "sbagliate",
    "lesson.explanation": "Spiegazione",
    "lesson.nextExercise": "Prossimo esercizio",
    "lesson.complete": "Lezione completata!",
    "lesson.earnedXP": "Hai guadagnato XP",
    "lesson.backHome": "Torna alla home",
    "lesson.continueCurriculum": "Continua curriculum",
    "lesson.excellentWork": "Ottimo lavoro, avventuriero!",
    "lesson.keepPracticing": "Continua a praticare per migliorare",
    "articles.library": "Biblioteca Articoli",
    "articles.introduction": "Introduzione",
    "articles.examples": "Esempi Pratici",
    "articles.commonMistakes": "Errori Comuni da Evitare",
    "articles.practiceExercises": "Esercizi di Pratica",
    "articles.summary": "Riassunto",
    "articles.relatedArticles": "Articoli Correlati",
    "articles.tableOfContents": "Contenuto",
    "articles.readTime": "min di lettura",
    "articles.showAnswer": "Mostra risposta",
    "articles.hideAnswer": "Nascondi risposta",
    "articles.hint": "Suggerimento",
    "articles.answer": "Risposta",
    "level.beginner": "Principiante",
    "level.elementary": "Elementare",
    "level.intermediate": "Intermedio",
    "level.upperIntermediate": "Intermedio Alto",
    "level.advanced": "Avanzato",
    "level.mastery": "Padronanza",
    "level.novice": "Novizio",
    "level.apprentice": "Apprendista",
    "level.adventurer": "Avventuriero",
    "level.warrior": "Guerriero",
    "level.master": "Maestro",
    "level.legend": "Leggenda",
    "category.grammar": "Grammatica",
    "category.vocabulary": "Vocabolario",
    "category.speaking": "Espressione Orale",
    "category.listening": "Comprensione Orale",
    "category.reading": "Comprensione Scritta",
    "category.writing": "Espressione Scritta",
    "language.select": "Seleziona lingua",
    "language.current": "Lingua attuale",
  },
  zh: {
    "nav.home": "首页",
    "nav.curriculum": "课程",
    "nav.grammar": "语法",
    "nav.vocabulary": "词汇",
    "nav.practice": "练习",
    "nav.conversation": "会话",
    "nav.tests": "测试",
    "nav.articles": "文章",
    "nav.settings": "设置",
    "common.back": "返回",
    "common.next": "下一个",
    "common.previous": "上一个",
    "common.start": "开始",
    "common.continue": "继续",
    "common.finish": "完成",
    "common.correct": "正确！",
    "common.incorrect": "错误",
    "common.score": "分数",
    "common.level": "等级",
    "common.exercise": "练习",
    "common.exercises": "练习",
    "common.of": "/",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功！",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.all": "全部",
    "common.none": "无",
    "common.yes": "是",
    "common.no": "否",
    "dashboard.welcome": "欢迎回来！",
    "dashboard.todayLesson": "今日课程",
    "dashboard.dailyGoal": "每日目标",
    "dashboard.streak": "连续天数",
    "dashboard.xp": "经验值",
    "dashboard.progress": "你的进度",
    "dashboard.continuelearning": "继续学习",
    "dashboard.adventureMap": "冒险地图",
    "dashboard.aiTutor": "AI导师",
    "dashboard.articleLibrary": "文章库",
    "lesson.overview": "概览",
    "lesson.practice": "练习",
    "lesson.objectives": "学习目标",
    "lesson.content": "练习内容",
    "lesson.startPractice": "开始练习",
    "lesson.beforeAnswer": "回答前请记住：",
    "lesson.listenQuestion": "听问题",
    "lesson.readArticle": "阅读完整文章",
    "lesson.correctAnswers": "正确",
    "lesson.incorrectAnswers": "错误",
    "lesson.explanation": "解释",
    "lesson.nextExercise": "下一题",
    "lesson.complete": "课程完成！",
    "lesson.earnedXP": "获得经验值",
    "lesson.backHome": "返回首页",
    "lesson.continueCurriculum": "继续课程",
    "lesson.excellentWork": "做得好，冒险家！",
    "lesson.keepPracticing": "继续练习以提高",
    "articles.library": "文章库",
    "articles.introduction": "介绍",
    "articles.examples": "实例",
    "articles.commonMistakes": "常见错误",
    "articles.practiceExercises": "练习题",
    "articles.summary": "总结",
    "articles.relatedArticles": "相关文章",
    "articles.tableOfContents": "目录",
    "articles.readTime": "分钟阅读",
    "articles.showAnswer": "显示答案",
    "articles.hideAnswer": "隐藏答案",
    "articles.hint": "提示",
    "articles.answer": "答案",
    "level.beginner": "初级",
    "level.elementary": "基础",
    "level.intermediate": "中级",
    "level.upperIntermediate": "中高级",
    "level.advanced": "高级",
    "level.mastery": "精通",
    "level.novice": "新手",
    "level.apprentice": "学徒",
    "level.adventurer": "冒险家",
    "level.warrior": "战士",
    "level.master": "大师",
    "level.legend": "传奇",
    "category.grammar": "语法",
    "category.vocabulary": "词汇",
    "category.speaking": "口语",
    "category.listening": "听力",
    "category.reading": "阅读",
    "category.writing": "写作",
    "language.select": "选择语言",
    "language.current": "当前语言",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.curriculum": "カリキュラム",
    "nav.grammar": "文法",
    "nav.vocabulary": "語彙",
    "nav.practice": "練習",
    "nav.conversation": "会話",
    "nav.tests": "テスト",
    "nav.articles": "記事",
    "nav.settings": "設定",
    "common.back": "戻る",
    "common.next": "次へ",
    "common.previous": "前へ",
    "common.start": "開始",
    "common.continue": "続ける",
    "common.finish": "終了",
    "common.correct": "正解！",
    "common.incorrect": "不正解",
    "common.score": "スコア",
    "common.level": "レベル",
    "common.exercise": "練習",
    "common.exercises": "練習",
    "common.of": "/",
    "common.loading": "読み込み中...",
    "common.error": "エラー",
    "common.success": "成功！",
    "common.cancel": "キャンセル",
    "common.save": "保存",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.search": "検索",
    "common.filter": "フィルター",
    "common.all": "すべて",
    "common.none": "なし",
    "common.yes": "はい",
    "common.no": "いいえ",
    "dashboard.welcome": "おかえりなさい！",
    "dashboard.todayLesson": "今日のレッスン",
    "dashboard.dailyGoal": "デイリー目標",
    "dashboard.streak": "連続日数",
    "dashboard.xp": "経験値",
    "dashboard.progress": "進捗",
    "dashboard.continuelearning": "学習を続ける",
    "dashboard.adventureMap": "アドベンチャーマップ",
    "dashboard.aiTutor": "AIチューター",
    "dashboard.articleLibrary": "記事ライブラリ",
    "lesson.overview": "概要",
    "lesson.practice": "練習",
    "lesson.objectives": "学習目標",
    "lesson.content": "練習内容",
    "lesson.startPractice": "練習を開始",
    "lesson.beforeAnswer": "答える前に覚えておいてください：",
    "lesson.listenQuestion": "質問を聞く",
    "lesson.readArticle": "記事を読む",
    "lesson.correctAnswers": "正解",
    "lesson.incorrectAnswers": "不正解",
    "lesson.explanation": "説明",
    "lesson.nextExercise": "次の問題",
    "lesson.complete": "レッスン完了！",
    "lesson.earnedXP": "獲得XP",
    "lesson.backHome": "ホームに戻る",
    "lesson.continueCurriculum": "カリキュラムを続ける",
    "lesson.excellentWork": "素晴らしい仕事です！",
    "lesson.keepPracticing": "練習を続けて上達しましょう",
    "articles.library": "記事ライブラリ",
    "articles.introduction": "はじめに",
    "articles.examples": "実例",
    "articles.commonMistakes": "よくある間違い",
    "articles.practiceExercises": "練習問題",
    "articles.summary": "まとめ",
    "articles.relatedArticles": "関連記事",
    "articles.tableOfContents": "目次",
    "articles.readTime": "分で読める",
    "articles.showAnswer": "答えを見る",
    "articles.hideAnswer": "答えを隠す",
    "articles.hint": "ヒント",
    "articles.answer": "答え",
    "level.beginner": "初級",
    "level.elementary": "基礎",
    "level.intermediate": "中級",
    "level.upperIntermediate": "中上級",
    "level.advanced": "上級",
    "level.mastery": "マスター",
    "level.novice": "初心者",
    "level.apprentice": "見習い",
    "level.adventurer": "冒険者",
    "level.warrior": "戦士",
    "level.master": "達人",
    "level.legend": "伝説",
    "category.grammar": "文法",
    "category.vocabulary": "語彙",
    "category.speaking": "スピーキング",
    "category.listening": "リスニング",
    "category.reading": "リーディング",
    "category.writing": "ライティング",
    "language.select": "言語を選択",
    "language.current": "現在の言語",
  },
  ko: {
    "nav.home": "홈",
    "nav.curriculum": "커리큘럼",
    "nav.grammar": "문법",
    "nav.vocabulary": "어휘",
    "nav.practice": "연습",
    "nav.conversation": "회화",
    "nav.tests": "테스트",
    "nav.articles": "기사",
    "nav.settings": "설정",
    "common.back": "뒤로",
    "common.next": "다음",
    "common.previous": "이전",
    "common.start": "시작",
    "common.continue": "계속",
    "common.finish": "완료",
    "common.correct": "정답!",
    "common.incorrect": "오답",
    "common.score": "점수",
    "common.level": "레벨",
    "common.exercise": "연습",
    "common.exercises": "연습",
    "common.of": "/",
    "common.loading": "로딩 중...",
    "common.error": "오류",
    "common.success": "성공!",
    "common.cancel": "취소",
    "common.save": "저장",
    "common.delete": "삭제",
    "common.edit": "편집",
    "common.search": "검색",
    "common.filter": "필터",
    "common.all": "전체",
    "common.none": "없음",
    "common.yes": "예",
    "common.no": "아니오",
    "dashboard.welcome": "다시 오신 것을 환영합니다!",
    "dashboard.todayLesson": "오늘의 수업",
    "dashboard.dailyGoal": "일일 목표",
    "dashboard.streak": "연속 일수",
    "dashboard.xp": "경험치",
    "dashboard.progress": "진행 상황",
    "dashboard.continuelearning": "학습 계속하기",
    "dashboard.adventureMap": "모험 지도",
    "dashboard.aiTutor": "AI 튜터",
    "dashboard.articleLibrary": "기사 라이브러리",
    "lesson.overview": "개요",
    "lesson.practice": "연습",
    "lesson.objectives": "학습 목표",
    "lesson.content": "연습 내용",
    "lesson.startPractice": "연습 시작",
    "lesson.beforeAnswer": "답하기 전에 기억하세요:",
    "lesson.listenQuestion": "질문 듣기",
    "lesson.readArticle": "기사 전문 읽기",
    "lesson.correctAnswers": "정답",
    "lesson.incorrectAnswers": "오답",
    "lesson.explanation": "설명",
    "lesson.nextExercise": "다음 문제",
    "lesson.complete": "수업 완료!",
    "lesson.earnedXP": "획득 XP",
    "lesson.backHome": "홈으로 돌아가기",
    "lesson.continueCurriculum": "커리큘럼 계속",
    "lesson.excellentWork": "훌륭합니다, 모험가!",
    "lesson.keepPracticing": "계속 연습하여 향상하세요",
    "articles.library": "기사 라이브러리",
    "articles.introduction": "소개",
    "articles.examples": "실용 예제",
    "articles.commonMistakes": "흔한 실수",
    "articles.practiceExercises": "연습 문제",
    "articles.summary": "요약",
    "articles.relatedArticles": "관련 기사",
    "articles.tableOfContents": "목차",
    "articles.readTime": "분 읽기",
    "articles.showAnswer": "답 보기",
    "articles.hideAnswer": "답 숨기기",
    "articles.hint": "힌트",
    "articles.answer": "답",
    "level.beginner": "초급",
    "level.elementary": "기초",
    "level.intermediate": "중급",
    "level.upperIntermediate": "중상급",
    "level.advanced": "고급",
    "level.mastery": "마스터",
    "level.novice": "초보자",
    "level.apprentice": "견습생",
    "level.adventurer": "모험가",
    "level.warrior": "전사",
    "level.master": "달인",
    "level.legend": "전설",
    "category.grammar": "문법",
    "category.vocabulary": "어휘",
    "category.speaking": "말하기",
    "category.listening": "듣기",
    "category.reading": "읽기",
    "category.writing": "쓰기",
    "language.select": "언어 선택",
    "language.current": "현재 언어",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.curriculum": "المنهج",
    "nav.grammar": "القواعد",
    "nav.vocabulary": "المفردات",
    "nav.practice": "التدريب",
    "nav.conversation": "المحادثة",
    "nav.tests": "الاختبارات",
    "nav.articles": "المقالات",
    "nav.settings": "الإعدادات",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.start": "ابدأ",
    "common.continue": "استمر",
    "common.finish": "إنهاء",
    "common.correct": "صحيح!",
    "common.incorrect": "خطأ",
    "common.score": "النتيجة",
    "common.level": "المستوى",
    "common.exercise": "تمرين",
    "common.exercises": "تمارين",
    "common.of": "من",
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجاح!",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.all": "الكل",
    "common.none": "لا شيء",
    "common.yes": "نعم",
    "common.no": "لا",
    "dashboard.welcome": "مرحبًا بعودتك!",
    "dashboard.todayLesson": "درس اليوم",
    "dashboard.dailyGoal": "الهدف اليومي",
    "dashboard.streak": "أيام متتالية",
    "dashboard.xp": "نقاط الخبرة",
    "dashboard.progress": "تقدمك",
    "dashboard.continuelearning": "واصل التعلم",
    "dashboard.adventureMap": "خريطة المغامرة",
    "dashboard.aiTutor": "معلم الذكاء الاصطناعي",
    "dashboard.articleLibrary": "مكتبة المقالات",
    "lesson.overview": "نظرة عامة",
    "lesson.practice": "تدريب",
    "lesson.objectives": "أهداف التعلم",
    "lesson.content": "محتوى التدريب",
    "lesson.startPractice": "ابدأ التدريب",
    "lesson.beforeAnswer": "قبل الإجابة، تذكر:",
    "lesson.listenQuestion": "استمع للسؤال",
    "lesson.readArticle": "اقرأ المقال كاملاً",
    "lesson.correctAnswers": "صحيحة",
    "lesson.incorrectAnswers": "خاطئة",
    "lesson.explanation": "الشرح",
    "lesson.nextExercise": "التمرين التالي",
    "lesson.complete": "اكتمل الدرس!",
    "lesson.earnedXP": "حصلت على XP",
    "lesson.backHome": "العودة للرئيسية",
    "lesson.continueCurriculum": "متابعة المنهج",
    "lesson.excellentWork": "عمل ممتاز، مغامر!",
    "lesson.keepPracticing": "استمر في التدريب للتحسن",
    "articles.library": "مكتبة المقالات",
    "articles.introduction": "مقدمة",
    "articles.examples": "أمثلة عملية",
    "articles.commonMistakes": "أخطاء شائعة",
    "articles.practiceExercises": "تمارين تدريبية",
    "articles.summary": "ملخص",
    "articles.relatedArticles": "مقالات ذات صلة",
    "articles.tableOfContents": "المحتويات",
    "articles.readTime": "دقيقة للقراءة",
    "articles.showAnswer": "إظهار الإجابة",
    "articles.hideAnswer": "إخفاء الإجابة",
    "articles.hint": "تلميح",
    "articles.answer": "الإجابة",
    "level.beginner": "مبتدئ",
    "level.elementary": "أساسي",
    "level.intermediate": "متوسط",
    "level.upperIntermediate": "فوق المتوسط",
    "level.advanced": "متقدم",
    "level.mastery": "إتقان",
    "level.novice": "مبتدئ",
    "level.apprentice": "متدرب",
    "level.adventurer": "مغامر",
    "level.warrior": "محارب",
    "level.master": "خبير",
    "level.legend": "أسطورة",
    "category.grammar": "القواعد",
    "category.vocabulary": "المفردات",
    "category.speaking": "التحدث",
    "category.listening": "الاستماع",
    "category.reading": "القراءة",
    "category.writing": "الكتابة",
    "language.select": "اختر اللغة",
    "language.current": "اللغة الحالية",
  },
  hi: {
    "nav.home": "होम",
    "nav.curriculum": "पाठ्यक्रम",
    "nav.grammar": "व्याकरण",
    "nav.vocabulary": "शब्दावली",
    "nav.practice": "अभ्यास",
    "nav.conversation": "बातचीत",
    "nav.tests": "परीक्षण",
    "nav.articles": "लेख",
    "nav.settings": "सेटिंग्स",
    "common.back": "वापस",
    "common.next": "अगला",
    "common.previous": "पिछला",
    "common.start": "शुरू करें",
    "common.continue": "जारी रखें",
    "common.finish": "समाप्त",
    "common.correct": "सही!",
    "common.incorrect": "गलत",
    "common.score": "स्कोर",
    "common.level": "स्तर",
    "common.exercise": "अभ्यास",
    "common.exercises": "अभ्यास",
    "common.of": "का",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफलता!",
    "common.cancel": "रद्द करें",
    "common.save": "सहेजें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.search": "खोजें",
    "common.filter": "फ़िल्टर",
    "common.all": "सभी",
    "common.none": "कोई नहीं",
    "common.yes": "हां",
    "common.no": "नहीं",
    "dashboard.welcome": "वापसी पर स्वागत है!",
    "dashboard.todayLesson": "आज का पाठ",
    "dashboard.dailyGoal": "दैनिक लक्ष्य",
    "dashboard.streak": "लगातार दिन",
    "dashboard.xp": "अनुभव",
    "dashboard.progress": "आपकी प्रगति",
    "dashboard.continuelearning": "सीखना जारी रखें",
    "dashboard.adventureMap": "साहसिक मानचित्र",
    "dashboard.aiTutor": "AI ट्यूटर",
    "dashboard.articleLibrary": "लेख पुस्तकालय",
    "lesson.overview": "अवलोकन",
    "lesson.practice": "अभ्यास",
    "lesson.objectives": "सीखने के उद्देश्य",
    "lesson.content": "अभ्यास सामग्री",
    "lesson.startPractice": "अभ्यास शुरू करें",
    "lesson.beforeAnswer": "जवाब देने से पहले याद रखें:",
    "lesson.listenQuestion": "प्रश्न सुनें",
    "lesson.readArticle": "पूरा लेख पढ़ें",
    "lesson.correctAnswers": "सही",
    "lesson.incorrectAnswers": "गलत",
    "lesson.explanation": "स्पष्टीकरण",
    "lesson.nextExercise": "अगला अभ्यास",
    "lesson.complete": "पाठ पूर्ण!",
    "lesson.earnedXP": "आपने XP कमाया",
    "lesson.backHome": "होम पर वापस",
    "lesson.continueCurriculum": "पाठ्यक्रम जारी रखें",
    "lesson.excellentWork": "शानदार काम, साहसी!",
    "lesson.keepPracticing": "सुधार के लिए अभ्यास जारी रखें",
    "articles.library": "लेख पुस्तकालय",
    "articles.introduction": "परिचय",
    "articles.examples": "व्यावहारिक उदाहरण",
    "articles.commonMistakes": "सामान्य गलतियां",
    "articles.practiceExercises": "अभ्यास प्रश्न",
    "articles.summary": "सारांश",
    "articles.relatedArticles": "संबंधित लेख",
    "articles.tableOfContents": "विषय सूची",
    "articles.readTime": "मिनट पढ़ने का समय",
    "articles.showAnswer": "उत्तर दिखाएं",
    "articles.hideAnswer": "उत्तर छुपाएं",
    "articles.hint": "संकेत",
    "articles.answer": "उत्तर",
    "level.beginner": "शुरुआती",
    "level.elementary": "प्राथमिक",
    "level.intermediate": "मध्यम",
    "level.upperIntermediate": "उच्च मध्यम",
    "level.advanced": "उन्नत",
    "level.mastery": "महारत",
    "level.novice": "नौसिखिया",
    "level.apprentice": "शिक्षु",
    "level.adventurer": "साहसी",
    "level.warrior": "योद्धा",
    "level.master": "गुरु",
    "level.legend": "किंवदंती",
    "category.grammar": "व्याकरण",
    "category.vocabulary": "शब्दावली",
    "category.speaking": "बोलना",
    "category.listening": "सुनना",
    "category.reading": "पढ़ना",
    "category.writing": "लिखना",
    "language.select": "भाषा चुनें",
    "language.current": "वर्तमान भाषा",
  },
  ru: {
    "nav.home": "Главная",
    "nav.curriculum": "Программа",
    "nav.grammar": "Грамматика",
    "nav.vocabulary": "Словарный запас",
    "nav.practice": "Практика",
    "nav.conversation": "Разговор",
    "nav.tests": "Тесты",
    "nav.articles": "Статьи",
    "nav.settings": "Настройки",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.previous": "Предыдущий",
    "common.start": "Начать",
    "common.continue": "Продолжить",
    "common.finish": "Завершить",
    "common.correct": "Правильно!",
    "common.incorrect": "Неправильно",
    "common.score": "Счёт",
    "common.level": "Уровень",
    "common.exercise": "Упражнение",
    "common.exercises": "Упражнения",
    "common.of": "из",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.success": "Успех!",
    "common.cancel": "Отмена",
    "common.save": "Сохранить",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.search": "Поиск",
    "common.filter": "Фильтр",
    "common.all": "Все",
    "common.none": "Нет",
    "common.yes": "Да",
    "common.no": "Нет",
    "dashboard.welcome": "С возвращением!",
    "dashboard.todayLesson": "Урок сегодня",
    "dashboard.dailyGoal": "Дневная цель",
    "dashboard.streak": "Серия",
    "dashboard.xp": "Опыт",
    "dashboard.progress": "Ваш прогресс",
    "dashboard.continuelearning": "Продолжить обучение",
    "dashboard.adventureMap": "Карта приключений",
    "dashboard.aiTutor": "ИИ Репетитор",
    "dashboard.articleLibrary": "Библиотека статей",
    "lesson.overview": "Обзор",
    "lesson.practice": "Практика",
    "lesson.objectives": "Цели обучения",
    "lesson.content": "Содержание для практики",
    "lesson.startPractice": "Начать практику",
    "lesson.beforeAnswer": "Перед ответом помните:",
    "lesson.listenQuestion": "Слушать вопрос",
    "lesson.readArticle": "Читать полную статью",
    "lesson.correctAnswers": "правильно",
    "lesson.incorrectAnswers": "неправильно",
    "lesson.explanation": "Объяснение",
    "lesson.nextExercise": "Следующее упражнение",
    "lesson.complete": "Урок завершён!",
    "lesson.earnedXP": "Вы заработали XP",
    "lesson.backHome": "Вернуться домой",
    "lesson.continueCurriculum": "Продолжить программу",
    "lesson.excellentWork": "Отличная работа, искатель приключений!",
    "lesson.keepPracticing": "Продолжайте практиковаться для улучшения",
    "articles.library": "Библиотека статей",
    "articles.introduction": "Введение",
    "articles.examples": "Практические примеры",
    "articles.commonMistakes": "Распространённые ошибки",
    "articles.practiceExercises": "Практические упражнения",
    "articles.summary": "Резюме",
    "articles.relatedArticles": "Связанные статьи",
    "articles.tableOfContents": "Содержание",
    "articles.readTime": "мин чтения",
    "articles.showAnswer": "Показать ответ",
    "articles.hideAnswer": "Скрыть ответ",
    "articles.hint": "Подсказка",
    "articles.answer": "Ответ",
    "level.beginner": "Начинающий",
    "level.elementary": "Элементарный",
    "level.intermediate": "Средний",
    "level.upperIntermediate": "Выше среднего",
    "level.advanced": "Продвинутый",
    "level.mastery": "Мастерство",
    "level.novice": "Новичок",
    "level.apprentice": "Ученик",
    "level.adventurer": "Искатель приключений",
    "level.warrior": "Воин",
    "level.master": "Мастер",
    "level.legend": "Легенда",
    "category.grammar": "Грамматика",
    "category.vocabulary": "Словарный запас",
    "category.speaking": "Говорение",
    "category.listening": "Аудирование",
    "category.reading": "Чтение",
    "category.writing": "Письмо",
    "language.select": "Выбрать язык",
    "language.current": "Текущий язык",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  languages: LanguageInfo[];
  currentLanguage: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "es";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
    document.documentElement.lang = language;
    // Set text direction for RTL languages
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: TranslationKey): string => {
    const langTranslations = translations[language] || translations.es;
    return langTranslations[key] || translations.es[key] || key;
  };

  const currentLanguage = languages.find(l => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
